### ISSUE TITLE
[style] code violates some go idioms

### ISSUE THREAD

**Issue by tmc** [logv/sybil#35]
In particular, golint has lots of complaints about variable and function naming.

**Comment by okayzed** [comment]
thanks for opening this issue! i have moderately strong feelings here, so i prefer not to make this set of changes. if you feel really strongly about this (and are going to contribute in the future), i am willing to consider renaming variables to fit go style. but again - i have strong feelings and every other go dev who comes into a project with an opinion about code style has caused me heart ache. 


**my longer thoughts**

one of go's main shortcomings is their linter's terrible opinions (and their programming community in general, i guess, but that's true of all languages). i'm of the notion that someone (the linter author presumably) went power mad: https://groups.google.com/forum/#!topic/golang-dev/XNEuZW6NIMM

using capitalization for public/private interfaces is stupid. not letting me having variables other than FooBar and fooBar is similarly stupid. I use FOO_BAR (global config var), foo_bar (local var), FooBar (class name) like a sane person. the fact their linter has opinions on this is too much (condensing 4 or 5 ways of naming and differentiating variables into only two acceptable ones). the linter should obviously have a way of turning on and off specific decisions, like variable names (snake_case) and ALL_UPPERS -  most every other linter out there allows for custom config. 

and for all that the google community talks about code style and modularity, i have yet to see many go packages that have an API you can use or extend easily, nor many projects that have plugin systems. often i have to go and modify the code and get a pull request in order to be able to use other people's libraries in projects of mine. 

i've actually gone through all the sybil code and re-factored it / renamed variables to look more Go like (because surprisingly, the go community really likes the linter and code style seems to be a pre-condition for go devs before they contribute). the only thing i can say is that i spent over a month on it and the potential contributor didn't end up contributing much other than their opinions on go style. 


https://github.com/logv/sybil/pull/10 <-- variable rename pull request i did
https://github.com/logv/sybil/pull/25 <-- "modular code" refactor i did.

**Comment by tmc** [comment]
No worries. I don’t actually care that much but I do like consistency and I
do think it can be a barrier. I’ve scripted converting the codebase and can
open a pr when I’m back at my machine.
